# Server config
server:
  port: 8082
# Spring config
spring:
  application:
    name: protected-service
  logging:
    level:
      org.springframework: INFO
      org.hibernate: WARN




# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# Ribbon config
ribbon:
  eureka:
    enabled: true