eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8080
spring:
  application:
    name: api-gateway
zuul:
  routes:
    authorize:
      path: /authorize/**
      service-id: authorize-service
    resource:
      path: /resource/**
      service-id: resource-service
  sensitive-headers: Cookie,Set-Cookie

  host:
    connect-timeout-millis: 60000 # starting the connection 
    socket-timeout-millis: 60000  # monitor the continuous incoming data flow
 